PLUGIN-496: Support syntax checking in BigQuery execute plugin - Integration Tests.
cdapio/cdap-integration-tests pull request #1119
Opened 2021-04-09 14:14 UTC by jasir99

Integration Tests for PLUGIN-496: Support syntax checking in BigQuery execute plugin.

Fix PR: https://github.com/data-integrations/google-cloud/pull/614
JIRA Ticket: https://cdap.atlassian.net/browse/PLUGIN-496

2021-04-12 09:14 UTC, flakrimjusufi requested changes

2021-04-12 09:14 UTC, flakrimjusufi commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryExecuteTest.java
> +
Please make sure you include java doc.

2021-04-12 09:14 UTC, flakrimjusufi commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryExecuteTest.java
> +    checkMetric(tags, "user." + source.getName() + ".records.out", 1, 10);
We can use String.Format() in checkMetric with more meaningful variable names. For example, instead of just putting 1, we can declare an int variable (something like _expectedCount_) and pass the value.

2021-04-12 09:14 UTC, flakrimjusufi commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryExecuteTest.java
> +    String sourceTableName = SOURCE_TABLE_NAME_TEMPLATE + testId;
We can use String.format() in here.

2021-04-12 09:14 UTC, flakrimjusufi commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryExecuteTest.java
> +      .put("rowAsArguments", "")
Is `rowAsArguments` default value empty string?

2021-04-13 19:14 UTC, rmstar approved these changes

2021-04-20 05:35 UTC, rmstar approved these changes
please squash commits

2021-04-20 16:59 UTC, merged