Intgrtn tests
cdapio/cdap-integration-tests pull request #1206
Opened 2022-11-28 08:39 UTC by udurbha

2022-12-05 10:20 UTC, DJSagarAhire requested changes
It's difficult to review PRs with high LOC counts - fixing the places where lines are changed without any resultant logical code changes should help the reviewer in reviewing PRs quickly.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/DedupAggregatorTest.java
> -    public static final String SMARTWORKFLOW_NAME = SmartWorkflow.NAME;
Please fix the whitespace diff

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/DedupAggregatorTest.java
> +    ETLStage userSourceStage = new ETLStage("users", new ETLPlugin("Table", BatchSource.PLUGIN_TYPE,
Please try to avoid changing code if there is no logical change, makes it difficult to review the PR and find the author of the code in future, particularly important during oncalls.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/DedupAggregatorTest.java
> +      ImmutableMap.<String, String>builder().put(Properties.BatchReadableWritable.NAME, USER_SINK)
Please try to avoid changing code if there is no logical change.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/DedupAggregatorTest.java
> +    ETLBatchConfig config = ETLBatchConfig.builder("* * * * *").addStage(userSourceStage)
Please try to avoid changing code if there is no logical change.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/DedupAggregatorTest.java
> -                .addConnection(userGroupStage.getName(), userSinkStage.getName())
Please try to avoid changing code if there is no logical change.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/DedupAggregatorTest.java
> -        ServiceManager serviceManager = applicationManager.getServiceManager
Please try to avoid changing code if there is no logical change.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/DedupAggregatorTest.java
> -                response, new TypeToken<Map<String, byte[]>>() { }.getType()).getResponseObject();
Please try to avoid changing code if there is no logical change.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +    .put("partitionFields", "profession")
Match indentation to `CONFIG_MAP_DEDUPE` above.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +    Map<String, byte[]> map = ObjectResponse.<Map<String, byte[]>>fromJsonBody( response, new
Please try to avoid changing code if there is no logical change.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +  private void putValues(Table purchaseTable, int index, long timestamp, String user, String item, long price) {
Please try to avoid changing code if there is no logical change.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +      ImmutableMap.<String, String>builder().put(Properties.BatchReadableWritable.NAME, name)
Please try to avoid changing code if there is no logical change.

2022-12-05 10:20 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +      new ETLPlugin("GroupByAggregate", BatchAggregator.PLUGIN_TYPE,  ImmutableMap.of("groupByFields", field,
Please try to avoid changing code if there is no logical change.

2022-12-05 10:35 UTC, udurbha commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +    .put("partitionFields", "profession")
Done

2022-12-05 10:56 UTC, DJSagarAhire reviewed
Please fix the whitespace-only diffs across all files (for real this time) and don't resolve comments until the commenter is satisfied with the resolution. Thanks!

2022-12-05 10:56 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/DedupAggregatorTest.java
> -    public static final String SMARTWORKFLOW_NAME = SmartWorkflow.NAME;
Please don't resolve comments on your own - let the original commenter resolve the comments if they feel the resolution is to their satisfaction. I still see indentation / whitespace changes, in particular this entire file is only whitespace changes.

2022-12-05 10:56 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +    Map<String, byte[]> map = ObjectResponse.<Map<String, byte[]>>fromJsonBody( response, new
This is not resolved, I still see a diff here.

2022-12-05 11:05 UTC, udurbha commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +    Map<String, byte[]> map = ObjectResponse.<Map<String, byte[]>>fromJsonBody( response, new
done

2022-12-06 09:47 UTC, DJSagarAhire reviewed
Mostly minor changes.

2022-12-06 09:47 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/WindowAggregatorTest.java
> +    new ArtifactSelectorConfig("USER", "window-aggregator", "1.0.2");
Can we pull the version number (1.0.2) into a separate constant? I see it is being used in many places and is likely to change frequently.

2022-12-06 09:47 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/WindowAggregatorTest.java
> +    ETLStage userGroupStage = new ETLStage("WindowAggregate", new ETLPlugin("WindowAggregation",
This stage can be renamed to indicate "window" somewhere.

2022-12-06 09:47 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/WindowAggregatorTest.java
> +  private Set<GenericRecord> readOutput(ServiceManager serviceManager, String sink, Schema schema)
I see some of the methods like `readOutput()`, `parseOutput()`, etc are mostly the same here and in `DedupAggregatorTest`. Could we take a JIRA to move these methods out of here into a superclass in the future?

2022-12-06 09:47 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +        artifactClient.getPluginSummaries(TEST_NAMESPACE.artifact("window-aggregation", "1.0.2"),
Same as above: version number for plugin to be moved to a constant.

2022-12-06 09:47 UTC, DJSagarAhire commented on integration-test-remote/src/test/java/io/cdap/cdap/test/suite/GCPSuite.java
> +  DLPTest.class,
Not sure why this change is required. If not, we'll need to undo the copyright change above as well.

2022-12-06 09:49 UTC, udurbha commented on integration-test-remote/src/test/java/io/cdap/cdap/test/suite/GCPSuite.java
> +  DLPTest.class,
This is to maintain the Alphabetical order

2022-12-06 10:03 UTC, udurbha commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/WindowAggregatorTest.java
> +  private Set<GenericRecord> readOutput(ServiceManager serviceManager, String sink, Schema schema)
https://cdap.atlassian.net/browse/CDAP-20175.Created

2022-12-06 10:05 UTC, udurbha commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/WindowAggregatorTest.java
> +    new ArtifactSelectorConfig("USER", "window-aggregator", "1.0.2");
Done

2022-12-06 10:05 UTC, udurbha commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/WindowAggregatorTest.java
> +    ETLStage userGroupStage = new ETLStage("WindowAggregate", new ETLPlugin("WindowAggregation",
Done

2022-12-06 10:06 UTC, udurbha commented on integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
> +        artifactClient.getPluginSummaries(TEST_NAMESPACE.artifact("window-aggregation", "1.0.2"),
Done

2022-12-06 10:10 UTC, DJSagarAhire approved these changes
LGTM

2022-12-06 10:11 UTC, merged